version: '3.8'

services:
  db:
    image: mysql
    container_name: biblio
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 747563616e
      MYSQL_DATABASE: Biblioteca
      MYSQL_USER: alex
      MYSQL_PASSWORD: 747563616e
    ports:
      - 3306:3306
    volumes:
      - ./db/:/docker-entrypoint-initdb.d/